"""
case desc: minimal create succeeds and returns widget id

@spec excerpt:
  Widget creation: tenant_id required; (tenant, name) unique.

handler:   handlers/widget.py
source:    handler @case('happy', ...)
"""

# AUTO-GENERATED scaffold by e2e-harness. Fill in the Case methods below.
# The meta block + the orchestrator at the bottom are regenerated by sync;
# do not edit them. Only edit `State` fields and `Case.prepare/run/clean` bodies.
# e2e-meta-start
# case_id:   happy
# case_hash: 00000001
# e2e-meta-end

import uuid
from dataclasses import dataclass

from e2e_harness.api.case import BaseState
from e2e_harness.api.case_rpc import RPCCase


@dataclass
class State(BaseState):
    created_id: str | None = None


class Case(RPCCase[State]):
    state_cls = State

    def run(self):
        name = f"widget-{uuid.uuid4().hex[:8]}"
        outcome = self.action_post("CreateWidget", {"Name": name})
        result = self.assert_action_success(outcome)
        widget_id = result.get("Id")
        assert isinstance(widget_id, str) and widget_id, f"missing Result.Id: {result!r}"
        self.state.created_id = widget_id

    def clean(self):
        if self.state.created_id:
            self.action_post("DeleteWidget", {"WidgetID": self.state.created_id})


# AUTO-GENERATED orchestrator: do not edit
def test_create_widget__happy(env, runner):
    Case(env, runner).execute()
